### ISSUE TITLE
Code for integrating audio

### ISSUE THREAD

**Issue by ncxa** [henrryzh1/UR-DMU#14]
Dear author, I need to ask you again because your work is fantastic. I would greatly appreciate it if you could provide the code file for the fused audio of xd-violence dataset.

**Comment by henrryzh1** [comment]
Thank you for your attention to our work. We only perform simple concatenation of audio data during the initial input. You can try modifying the dataset reading process, and I believe this is a simple task.

**Comment by ncxa** [comment]
Thanks,for your reply

**Comment by g566521** [comment]
Have you completed this task? After integrating the audio, what experiments need to be done? Which part of the dataset should be used?

**Comment by g566521** [comment]
> Thanks,for your reply

Have you completed this task? After integrating the audio, what experiments need to be done? Which part of the dataset should be used?
