### ISSUE TITLE
About the code and equation 5 in the paper

### ISSUE THREAD

**Issue by YukiFan** [henrryzh1/UR-DMU#2]
Thanks for sharing the code of this excellent work. But I have some questions about the code and the paper.  It will be much appreciated if you could resolve my puzzles.

for code:  in model.py, "anchor_nx_new = torch.gather(N_aug_new, 1, A_index.unsqueeze(2).expand([-1, -1, x.size(-1)])).mean(1).reshape(b // 2, n, -1).mean(1) "  "A_index" seems wrong, may be "N_index"？

for paper:  In equation (5) y_nn, y_an, y_aa are all equal to 1, and y_na is equal to 0. 
Although in paper there exists “The first two terms of Ldm limit the normal memory unit to learn normal patterns, and the last two terms ensure the abnormal pattern learning for abnormal memory unit.”  I still can't understand  (＠_＠;), could you give me more explanation about why choose 1 or 0 for these four items?

**Comment by henrryzh1** [comment]
You can carefully read section 3.3 of our paper.

For code:

```python
anchor_nx_new = torch.gather(N_aug_new, 1, A_index.unsqueeze(2).expand([-1, -1, x.size(-1)])).mean(1).reshape(b // 2, n, -1).mean(1)
```

Thank you for your careful review of the code, we will correct this error.

For paper: 

- In equation(5). The first two terms $BCE(S_{k;n}^n,\mathbb y_n^n)+BCE(S_{k;a}^n,\mathbb y_a^n)$ describe an normal video(no abnormal segments) input into the two memory block, so the output $S_{k;n}^n$ of N_mem(normal) should be [1,1,...,1] all ones, $S_{k;a}^n$ of A_mem(abnormal) should be [0,0,...,0] all zeros. 

- The last two terms $BCE(S_{k;n;k}^a,y_n^n)+BCE(S_{k;a;k}^a,y_a^n)$ describe an abnormal video(et least one abnormal segment) input into the two memory blocks,  $S_{k;n}^a$ of N_mem(normal) should be [1,0,...,0] at least one, $S_{k;n;k}^a$ chooses the topK score. $S_{k;a}^a$ of A_mem(abnormal) also should be [0,0,...,1] at least ones, $S_{k;a;k}^a$ chooses the topK score. You can think it with Fig.3.
