### ISSUE TITLE
About  UCF auc

### ISSUE THREAD

**Issue by Yixiaochuan628** [henrryzh1/UR-DMU#7]
"I would like to inquire about the process of reproducing the AUC score for UCF by the authors. Why am I only getting around 85.68?

**Comment by Yixiaochuan628** [comment]
but  i also find someone auc is 86.3 ，so what are the differences then?

**Comment by Yixiaochuan628** [comment]
I found that the larger the batch size, the better the AUC performance. maybe  it related to the memory。

**Comment by StartBear0** [comment]
> "I would like to inquire about the process of reproducing the AUC score for UCF by the authors. Why am I only getting around 85.68?

Hello, may I ask if you used the features downloaded from the link provided by the author, or if you obtained the features by running the I3D code? I followed the I3D feature extraction steps to obtain the features, but the reproduced result only has an AUC of 0.68.

**Comment by Anushaacharya607** [comment]
@Yixiaochuan628, what batch size did you use to reproduce the AUC score? I'm stuck at 85.70.
