### ISSUE TITLE
about datasets

### ISSUE THREAD

**Issue by fangxinGod** [henrryzh1/UR-DMU#9]
Dear Teacher Author,
Hello, I would like to ask about the overall structure of the dataset you used for training or inference. During the process of reproduction, I encountered the following two minor issues, and I suspect that there might be a problem with the structure of my dataset, or there might be an error in my reproduction process. Could you please help me clarify this?
![Uploading QQ图片20240830165456.png…]()
![Uploading QQ图片20240830165500.png…]()

**Comment by henrryzh1** [comment]
Thank you for paying attention to our work. I can't see the screenshot you provided. Please show your question again.

**Comment by fangxinGod** [comment]
> Thank you for paying attention to our work. I can't see the screenshot you provided. Please show your question again.

Thank you teacher for your reply. I would like to ask what is the organizational structure of the data set. Can you post a picture if it is convenient?

**Comment by fangxinGod** [comment]
ValueError: too many values to unpack (expected 2)

And what is the reason for this error?

**Comment by twmht** [comment]
@henrryzh1 

May I ask if this code is executable? I'm encountering the same issue, as I also get an error when running ucf_main.py

for example, the dataloader return data,label,name but you only expect data,label

https://github.com/henrryzh1/UR-DMU/blob/master/ucf_test.py#L30

**Comment by fangxinGod** [comment]
> Thank you for paying attention to our work. I can't see the screenshot you provided. Please show your question again.
requests.exceptions.ConnectionError: ('Connection aborted.', BadStatusLine('SSH-2.0-OpenSSH_8.9p1 Ubuntu-3ubuntu0.10\r\n'))
  2%|███▏                                                                                                                                                                                         | 51/3000 [07:05<18:03:03, 22.04s/it]
Is this running away?
